# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.NilsEstimate <- function(r_ordered_psu_size, r_cat_psu, r_tracts, r_plot_data, area, tract_area) {
    .Call('_nilsier_NilsEstimate', PACKAGE = 'nilsier', r_ordered_psu_size, r_cat_psu, r_tracts, r_plot_data, area, tract_area)
}

.NilsBalancedEstimate <- function(r_ordered_psu_size, r_cat_psu, r_tracts, r_plot_data, area, tract_area, r_xbalance) {
    .Call('_nilsier_NilsBalancedEstimate', PACKAGE = 'nilsier', r_ordered_psu_size, r_cat_psu, r_tracts, r_plot_data, area, tract_area, r_xbalance)
}

